export {default as Navbar} from './Navbar/Navbar'
export {default as Empty} from './Empty'
export {default as Socials} from './Socials/Social'
export {default as HeroSection} from './HeroSection/HeroSection'
export {default as Progress} from './Progress/Progress'
export {default as About } from './About/About'
export {default as Projects} from './Project/Project'
export {default as Services} from './Service/Service'
export {default as Contact} from './Contact/Contact'
export {default as Footer} from './Footer/Footer'